import { mkdir, readdir, readFile, writeFile } from "fs/promises";
import { resolve } from "path";
import { pathToFileURL } from "url";

type AdapterSources = Record<string, string[]>;

type ResolvedFile = {
  path: string;
  order: number;
  content: string;
};

type ConsumerBundle = {
  consumer: string;
  patterns: string[];
  files: ResolvedFile[];
};

export type ResolutionReport = {
  generatedAt: string;
  outputDir: string;
  consumers: Array<{
    consumer: string;
    fileCount: number;
    patterns: string[];
  }>;
};

const REPO_ROOT = process.cwd();
const OUTPUT_DIR = resolve(REPO_ROOT, "instructions/generated");

async function listFilesInDirectory(dirPath: string): Promise<string[]> {
  const entries = await readdir(dirPath, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile())
    .map((entry) => resolve(dirPath, entry.name));
}

function toRepoRelative(absolutePath: string): string {
  const normalized = absolutePath.replaceAll("\\", "/");
  const root = REPO_ROOT.replaceAll("\\", "/");
  return normalized.startsWith(`${root}/`) ? normalized.slice(root.length + 1) : normalized;
}

function parseYamlBlockList(yamlText: string, key: string): string[] {
  const lines = yamlText.split(/\r?\n/);
  const result: string[] = [];
  let inBlock = false;

  for (const line of lines) {
    if (!inBlock) {
      if (line.trim() === `${key}:`) {
        inBlock = true;
      }
      continue;
    }

    if (/^\S/.test(line)) {
      break;
    }

    const itemMatch = line.match(/^\s*-\s+(.+)$/);
    if (itemMatch) {
      result.push(itemMatch[1].trim());
      continue;
    }

    if (line.trim().length > 0 && !line.includes("- ")) {
      break;
    }
  }

  return result;
}

function parseAdapterSources(yamlText: string): AdapterSources {
  const lines = yamlText.split(/\r?\n/);
  const adapters: AdapterSources = {};

  let inAdapters = false;
  let currentAdapter: string | null = null;
  let inSourceOfTruth = false;

  for (const line of lines) {
    if (!inAdapters) {
      if (line.trim() === "adapters:") {
        inAdapters = true;
      }
      continue;
    }

    if (line.trim() === "notes:") {
      break;
    }

    const adapterMatch = line.match(/^\s{2}([a-zA-Z0-9_-]+):\s*$/);
    if (adapterMatch) {
      currentAdapter = adapterMatch[1];
      adapters[currentAdapter] = [];
      inSourceOfTruth = false;
      continue;
    }

    if (currentAdapter && line.match(/^\s{4}source_of_truth:\s*$/)) {
      inSourceOfTruth = true;
      continue;
    }

    if (inSourceOfTruth) {
      const sourceMatch = line.match(/^\s{6}-\s+(.+)$/);
      if (sourceMatch && currentAdapter) {
        adapters[currentAdapter].push(sourceMatch[1].trim());
        continue;
      }

      if (line.match(/^\s{4}[a-zA-Z0-9_-]+:\s*/)) {
        inSourceOfTruth = false;
      }
    }
  }

  return adapters;
}

async function expandPattern(pattern: string): Promise<string[]> {
  if (!pattern.includes("*")) {
    const absolute = resolve(REPO_ROOT, pattern);
    return [absolute];
  }

  const wildcardIndex = pattern.indexOf("*");
  const slashBeforeWildcard = pattern.lastIndexOf("/", wildcardIndex);
  const folderPart = pattern.slice(0, slashBeforeWildcard);
  const filePattern = pattern.slice(slashBeforeWildcard + 1);

  const extensionMatch = filePattern.match(/\*\.(.+)$/);
  const extension = extensionMatch ? `.${extensionMatch[1]}` : null;

  const absoluteFolder = resolve(REPO_ROOT, folderPart);
  const files = await listFilesInDirectory(absoluteFolder);

  return files
    .filter((file) => (extension ? file.endsWith(extension) : true))
    .sort((a, b) => a.localeCompare(b));
}

async function buildResolvedFiles(patterns: string[]): Promise<ResolvedFile[]> {
  const seen = new Set<string>();
  const resolved: ResolvedFile[] = [];
  let order = 0;

  for (const pattern of patterns) {
    if (pattern === "user-request") {
      continue;
    }

    const paths = await expandPattern(pattern);
    for (const absolutePath of paths) {
      const relativePath = toRepoRelative(absolutePath);
      if (seen.has(relativePath)) {
        continue;
      }
      seen.add(relativePath);

      const content = await readFile(absolutePath, "utf8");
      resolved.push({
        path: relativePath,
        order,
        content,
      });
      order += 1;
    }
  }

  return resolved;
}

function toMarkdownBundle(bundle: ConsumerBundle): string {
  const header = [
    `# Instruction Bundle: ${bundle.consumer}`,
    "",
    "Generated by `npm run instructions:resolve`.",
    "",
    "## Source patterns",
    ...bundle.patterns.map((pattern) => `- ${pattern}`),
    "",
    "## Ordered files",
    ...bundle.files.map((file) => `- [${file.order}] ${file.path}`),
    "",
    "## Concatenated content",
    "",
  ];

  const sections = bundle.files.map(
    (file) => `### ${file.path}\n\n\`\`\`text\n${file.content}\n\`\`\``
  );

  return [...header, ...sections].join("\n");
}

export async function resolveInstructionLayer(): Promise<ResolutionReport> {
  const manifestPath = resolve(REPO_ROOT, "instructions/manifest.yaml");
  const adaptersPath = resolve(REPO_ROOT, "configs/adapters.yaml");

  const [manifestText, adaptersText] = await Promise.all([
    readFile(manifestPath, "utf8"),
    readFile(adaptersPath, "utf8"),
  ]);

  const resolutionOrder = parseYamlBlockList(manifestText, "resolution_order");
  const adapterSources = parseAdapterSources(adaptersText);

  const consumers = Object.keys(adapterSources);
  if (consumers.length === 0) {
    throw new Error("No consumers found in configs/adapters.yaml");
  }

  await mkdir(OUTPUT_DIR, { recursive: true });

  const bundles: ConsumerBundle[] = [];

  for (const consumer of consumers) {
    const patterns = adapterSources[consumer];
    const fallbackPatterns = resolutionOrder.filter((entry) => entry !== "user-request");
    const effectivePatterns = patterns.length > 0 ? patterns : fallbackPatterns;

    const files = await buildResolvedFiles(effectivePatterns);
    const bundle: ConsumerBundle = {
      consumer,
      patterns: effectivePatterns,
      files,
    };
    bundles.push(bundle);

    const jsonOutputPath = resolve(OUTPUT_DIR, `${consumer}.bundle.json`);
    const markdownOutputPath = resolve(OUTPUT_DIR, `${consumer}.bundle.md`);

    await writeFile(
      jsonOutputPath,
      JSON.stringify(
        {
          consumer: bundle.consumer,
          patterns: bundle.patterns,
          files: bundle.files.map((file) => ({ path: file.path, order: file.order })),
        },
        null,
        2
      ) + "\n",
      "utf8"
    );

    await writeFile(markdownOutputPath, toMarkdownBundle(bundle), "utf8");
  }

  const reportPath = resolve(OUTPUT_DIR, "resolution-report.json");
  const report: ResolutionReport = {
    generatedAt: new Date().toISOString(),
    outputDir: toRepoRelative(OUTPUT_DIR),
    consumers: bundles.map((bundle) => ({
      consumer: bundle.consumer,
      fileCount: bundle.files.length,
      patterns: bundle.patterns,
    })),
  };

  await writeFile(
    reportPath,
    JSON.stringify(report, null, 2) + "\n",
    "utf8"
  );

  return report;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  resolveInstructionLayer()
    .then((report) => {
      console.log(`Instruction bundles generated at ${report.outputDir}.`);
      for (const consumer of report.consumers) {
        console.log(`- ${consumer.consumer}: ${consumer.fileCount} files`);
      }
    })
    .catch((error) => {
      console.error("Failed to resolve instruction layer:", error);
      process.exit(1);
    });
}
